user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Definició de la memòria cau
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

    # Balanceig de càrrega Round Robin (per defecte)
    upstream backends {
        server apache1:80;
        server apache2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backends;
            
            # Configuració del proxy
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Configuració de la memòria cau
            proxy_cache my_cache;
            proxy_cache_valid 200 10m;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            
            # Capçalera per verificar si és HIT o MISS
            add_header X-Cache-Status $upstream_cache_status;
            # Capçalera per identificar el backend (útil per a captures de pantalla)
            add_header X-Backend-Server $upstream_addr;
        }
    }
}
